import test from 'node:test';
import assert from 'node:assert/strict';
import {viewerFetch,isVerifiedViewer} from '../dist/server/admin-viewer.mjs';
import worker from '../dist/server/index.js';
const origin='https://example.com';
const hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('adminadmin'))).toString('hex');
function environment(){const counts=new Map();return {TEMP_ADMIN_USERNAME:'test.satingraphic.ca',TEMP_ADMIN_PASSWORD_HASH:hash,TEMP_ADMIN_SESSION_SECRET:'a'.repeat(64),DB:{prepare(sql){let args;return {bind(...a){args=a;return this;},async first(){return counts.has(args[0])?{value:String(counts.get(args[0]))}:null;},async run(){counts.set(args[0],(counts.get(args[0])||0)+1);return {meta:{changes:1}};}};}}};}
const login=(password='adminadmin')=>new Request(origin+'/admin/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/x-www-form-urlencoded','CF-Connecting-IP':'192.0.2.1'},body:new URLSearchParams({username:'test.satingraphic.ca',password})});
const app={fetch:r=>new Response('<html><head></head><body>Owner account</body></html>',{status:isVerifiedViewer(r)?200:403,headers:{'Content-Type':'text/html'}})};
test('temporary login gives a secure signed view-only session',async()=>{const env=environment(),response=await viewerFetch(login(),env,app);assert.equal(response.status,303);const setCookie=response.headers.get('Set-Cookie');for(const flag of ['Secure','HttpOnly','SameSite=Strict'])assert.ok(setCookie.includes(flag));const cookie=setCookie.split(';')[0];const page=await viewerFetch(new Request(origin+'/admin/',{headers:{Cookie:cookie}}),env,app);assert.equal(page.status,200);assert.match(await page.text(),/view-only.js/);const write=await viewerFetch(new Request(origin+'/api/admin/pricing',{method:'POST',headers:{Cookie:cookie}}),env,{fetch(){throw Error('Mutation must never reach application');}});assert.equal(write.status,403);});
test('tampered and expired cookies cannot grant access',async()=>{const env=environment(),response=await viewerFetch(login(),env,app);const cookie=response.headers.get('Set-Cookie').split(';')[0];for(const value of [cookie+'a',cookie.replace(/=\d+\./,'=1000000000000.')]){const denied=await viewerFetch(new Request(origin+'/admin/',{headers:{Cookie:value}}),env,app);assert.equal(denied.status,302);assert.equal(denied.headers.get('Location'),origin+'/admin/login');}});
test('incorrect passwords are throttled and cross-origin login is rejected',async()=>{const env=environment();for(let n=0;n<8;n++)assert.equal((await viewerFetch(login('wrong'),env,app)).status,401);assert.equal((await viewerFetch(login('wrong'),env,app)).status,429);const wrongOrigin=login();wrongOrigin.headers.set('Origin','https://other.example');assert.equal((await viewerFetch(wrongOrigin,environment(),app)).status,403);});
test('email viewer gets reads, cannot write, and a client marker is ignored',async()=>{const headers={'oai-authenticated-user-id':'viewer','oai-authenticated-user-email':'p.moeini67@gmail.com'};assert.equal((await viewerFetch(new Request(origin+'/admin/',{headers}),environment(),app)).status,200);assert.equal((await viewerFetch(new Request(origin+'/api/admin/products',{method:'POST',headers}),environment(),app)).status,403);const forged=await viewerFetch(new Request(origin+'/api/admin/products',{headers:{'x-satin-verified-viewer':'1'}}),environment(),app);assert.equal(forged.status,403);});
test('owner write requests still reach the application',async()=>{let called=false;const response=await viewerFetch(new Request(origin+'/api/admin/products',{method:'POST',headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'mehrad.tr@gmail.com'}}),environment(),{fetch(){called=true;return new Response('owner');}});assert.equal(response.status,200);assert.ok(called);});
test('viewer banner script is added even when static assets omit their content type',async()=>{const env=environment(),response=await viewerFetch(login(),env,app),cookie=response.headers.get('Set-Cookie').split(';')[0];const result=await viewerFetch(new Request(origin+'/admin/',{headers:{Cookie:cookie}}),env,{fetch:()=>new Response('<!doctype html><title>Management</title>')});assert.match(await result.text(),/view-only.js/);});
test('actual worker permits viewer admin reads and rejects writes',async()=>{const env=environment(),signed=await worker.fetch(login(),env);const cookie=signed.headers.get('Set-Cookie').split(';')[0];const response=await worker.fetch(new Request(origin+'/api/admin/pricing',{headers:{Cookie:cookie}}),env);assert.equal(response.status,200);assert.ok((await response.json()).bases);assert.equal((await worker.fetch(new Request(origin+'/api/admin/pricing',{method:'POST',headers:{Cookie:cookie}}),env)).status,403);assert.equal((await worker.fetch(new Request(origin+'/api/admin/pricing',{headers:{'x-satin-verified-viewer':'1'}}),env)).status,403);});
test('developer mode permits validated admin writes and removes read-only UI',async()=>{const env={...environment(),TEMP_ADMIN_ACCESS_MODE:'admin'},signed=await worker.fetch(login(),env),cookie=signed.headers.get('Set-Cookie').split(';')[0];const get=await worker.fetch(new Request(origin+'/api/admin/pricing',{headers:{Cookie:cookie}}),env),pricing=await get.json();const write=await worker.fetch(new Request(origin+'/api/admin/pricing',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(pricing)}),env);assert.equal(write.status,200);assert.deepEqual(await write.json(),{saved:true});const page=await viewerFetch(new Request(origin+'/admin/',{headers:{Cookie:cookie}}),env,app),html=await page.text();assert.match(html,/admin-access.js/);assert.doesNotMatch(html,/view-only.js/);assert.match(html,/Developer account/);const emailWrite=await viewerFetch(new Request(origin+'/api/admin/products',{method:'POST',headers:{'oai-authenticated-user-id':'developer','oai-authenticated-user-email':'p.moeini67@gmail.com'}}),env,{fetch:r=>new Response(isVerifiedViewer(r)?'allowed':'denied',{status:isVerifiedViewer(r)?200:403})});assert.equal(emailWrite.status,200);});
