import {fileURLToPath} from 'node:url';
import {worker,env,db} from './checkout.test.mjs';import assert from 'node:assert/strict';
const origin='https://satin.test';let cookie='';async function call(path,data){const r=await worker.fetch(new Request(origin+path,data===undefined?{headers:{Cookie:cookie}}:{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)}),env);if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,body:await r.json()};}
await call('/api/studio/session',{});let state=(await call('/api/checkout/draft')).body;async function change(path,data){const r=await call('/api/checkout/'+path,{revision:state.revision,...data});assert.equal(r.status,200,JSON.stringify(r.body));state=r.body;}
await change('import',{items:[{id:'paid-test',pricing:{ruleId:'print-business-cards',values:{quantity:500,print_sides:0,design:1}}}]});assert.equal(state.draft.items[0].designRequested,true);assert.equal(state.draft.items[0].price.net,12600);await change('shipping',{address:{name:'Customer',email:'test@example.com',street1:'50 Viceroy Rd',city:'Vaughan',state:'ON',zip:'L4K 3A9',country:'CA'}});await change('select-shipping',{id:'gta-next-day'});assert.equal(state.totals.tax,2288);assert.equal(state.totals.total,19888);
const revision=state.revision;const duplicate=await call('/api/checkout/import',{revision,items:[{id:'paid-test',pricing:{ruleId:'print-business-cards',values:{quantity:500,design:1}}}]});assert.equal(duplicate.body.revision,revision);assert.equal(duplicate.body.draft.shipping.id,'gta-next-day');
assert.equal((await call('/api/checkout/payment',{revision,provider:'square',consent:true})).status,503);env.CHECKOUT_PAYMENTS_ENABLED='true';env.SQUARE_ACCESS_TOKEN='fake-test-token';env.SQUARE_LOCATION_ID='TEST-LOCATION';env.SQUARE_WEBHOOK_SIGNATURE_KEY='test-webhook';let providerOrder,createCalls=0,paid=false,wrongAmount=false;const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options={})=>{const u=new URL(url);assert.equal(u.hostname,'connect.squareup.com');if(u.pathname==='/v2/online-checkout/payment-links'){createCalls++;const p=JSON.parse(options.body);assert.equal(p.checkout_options.enable_coupon,false);assert.equal(p.order.taxes[0].percentage,'13');assert.equal(p.order.line_items.length,2);const base=p.order.line_items.reduce((n,i)=>n+i.base_price_money.amount,0),total=base+Math.round(base*13/100);assert.equal(total,19888);providerOrder={id:'SQUARE-ORDER',location_id:'TEST-LOCATION',reference_id:p.order.reference_id,total_money:{amount:total,currency:'CAD'},tenders:[]};return Response.json({payment_link:{order_id:'SQUARE-ORDER',url:'https://square.link/u/test'},related_resources:{orders:[providerOrder]}});}if(u.pathname==='/v2/orders/SQUARE-ORDER')return Response.json({order:{...providerOrder,tenders:paid?[{payment_id:'PAYMENT'}]:[]}});if(u.pathname==='/v2/payments/PAYMENT')return Response.json({payment:{status:'COMPLETED',order_id:providerOrder.id,location_id:'TEST-LOCATION',amount_money:{amount:wrongAmount?19887:19888,currency:'CAD'}}});throw Error('Unexpected gateway '+u.pathname);};
try{const started=await call('/api/checkout/payment',{revision,provider:'square',consent:true,total:1});assert.equal(started.status,200);const id=started.body.order.id;assert.equal(started.body.order.status,'awaiting_payment');assert.equal(started.body.order.snapshot.totals.total,19888);const again=await call('/api/checkout/payment',{revision,provider:'square',consent:true});assert.equal(again.body.order.id,id);assert.equal(createCalls,1);assert.equal((await call('/api/checkout/order?id='+id)).body.order.status,'awaiting_payment');paid=true;wrongAmount=true;assert.equal((await call('/api/checkout/order?id='+id)).body.order.status,'awaiting_payment');wrongAmount=false;assert.equal((await call('/api/checkout/order?id='+id)).body.order.status,'paid');assert.equal((await call('/api/checkout/order?id='+id)).body.order.status,'paid');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM service_requests WHERE id=?').get(id).n,1);const details=JSON.parse(db.prepare('SELECT details FROM service_requests WHERE id=?').get(id).details);assert.equal(details.paymentStatus,'paid');assert.equal(details.preflightStatus,'awaiting_production_review');cookie='';await call('/api/studio/session',{});assert.equal((await call('/api/checkout/order?id='+id)).status,404);
console.log('PASS: Square adapter (mock provider): authoritative CAD totals, tax/shipping, product design fee $100, idempotency, verified amount, private orders, paid-only order entry.');}finally{globalThis.fetch=originalFetch;delete env.SQUARE_WEBHOOK_SIGNATURE_KEY;delete env.SQUARE_ACCESS_TOKEN;delete env.SQUARE_LOCATION_ID;delete env.CHECKOUT_PAYMENTS_ENABLED;}
