from pathlib import Path
# Wall-only composition. Base photo is drawn, customer image clipped to wall, foreground stays above it.
for p in ['dist/server/service-pages.mjs','dist/client/services-ui.mjs']:
 s=Path(p).read_text();a=s.index('function mountRoomPreview(box)');s=s[:a]+'''function mountRoomPreview(box){const host=document.querySelector('[data-room-preview]');if(!host)return;const canvas=host.querySelector('canvas');canvas.width=768;canvas.height=512;const ctx=canvas.getContext('2d');let art=null,zoom=1,offsetX=0,offsetY=0,background=null,drag=null;const old=host.querySelector('[data-room]')?.parentElement;if(old)old.remove();const controls=document.createElement('div');controls.className='wall-controls';controls.innerHTML='<label>Artwork size<input type="range" min="1" max="4" step=".01" value="1" data-wall-zoom></label><label>Horizontal position<input type="range" min="-384" max="384" value="0" data-wall-x></label><label>Vertical position<input type="range" min="-333" max="333" value="0" data-wall-y></label><p class="small">Drag your image on the wall. Furniture is kept on a separate foreground layer.</p>';canvas.after(controls);const draw=()=>{if(!background)return;ctx.clearRect(0,0,768,512);ctx.drawImage(background,0,0,768,512);if(art){const scale=Math.max(768/art.width,333/art.height)*zoom;ctx.save();ctx.beginPath();ctx.rect(0,0,768,333);ctx.clip();ctx.drawImage(art,(768-art.width*scale)/2+offsetX,(333-art.height*scale)/2+offsetY,art.width*scale,art.height*scale);ctx.globalCompositeOperation='multiply';ctx.globalAlpha=.13;ctx.drawImage(background,0,0,768,512);ctx.restore();}};const scene=new Image();scene.onload=()=>{background=scene;draw();};scene.onerror=()=>{host.insertAdjacentHTML('beforeend','<p role="alert">Room preview could not load. Retry or contact info@satingraphic.ca.</p>');};scene.src='/satin/img/wall-room.png';controls.oninput=e=>{if(e.target.hasAttribute('data-wall-zoom'))zoom=Number(e.target.value);if(e.target.hasAttribute('data-wall-x'))offsetX=Number(e.target.value);if(e.target.hasAttribute('data-wall-y'))offsetY=Number(e.target.value);draw();};canvas.style.touchAction='none';canvas.onpointerdown=e=>{if(!art)return;drag={x:e.clientX,y:e.clientY,ox:offsetX,oy:offsetY};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const r=canvas.getBoundingClientRect();offsetX=drag.ox+(e.clientX-drag.x)*768/r.width;offsetY=drag.oy+(e.clientY-drag.y)*512/r.height;draw();};canvas.onpointerup=()=>{drag=null;};canvas.onpointercancel=()=>{drag=null;};box.addEventListener('change',e=>{if(e.target.matches('[data-art-upload]')){const file=e.target.files[0];if(!['image/png','image/jpeg','image/webp'].includes(file?.type)||file.size>20000000)return;const url=URL.createObjectURL(file),im=new Image();im.onload=()=>{art=im;zoom=1;offsetX=offsetY=0;draw();URL.revokeObjectURL(url);};im.src=url;}});}
''';s=s.replace('PNG, JPG, WebP or PDF','PNG, JPG or WebP images');Path(p).write_text(s)
# Digital files can be attached by the owner in the product editor.
p=Path('dist/client/admin/products.mjs');s=p.read_text().replace('<h3>Downloadable PDF templates</h3>','<h3>Paid digital artwork file</h3><p>Upload the final vector or ZIP sold with this product. Buyers receive it only after verified payment.</p><input type="file" data-digital-upload accept=".svg,.pdf,.ai,.eps,.zip"><p data-digital-status></p><h3>Downloadable PDF templates</h3>');s=s.replace("const form=$('[data-product-form]');let uploading=0;", "const form=$('[data-product-form]');let uploading=0;form.querySelector('[data-digital-upload]').onchange=async e=>{const file=e.target.files[0];if(!file)return;uploading++;try{const fd=new FormData();fd.set('ruleId',rule.id);fd.set('file',file);const r=await fetch('/api/admin/digital-upload',{method:'POST',body:fd}),v=await r.json();if(!r.ok)throw Error(v.error);form.querySelector('[data-digital-status]').textContent='Paid download attached: '+v.name;}catch(err){form.querySelector('[data-digital-status]').textContent=err.message;}finally{uploading--;}};");p.write_text(s)
# Adjust design is an optional service, print & installation routes to quote.
p=Path('dist/server/batch-updates.mjs');s=p.read_text().replace("r.id.startsWith('wrap-design-')", "r.id.startsWith('design-')&&r.id!=='design-services'");p.write_text(s)
p=Path('dist/client/batch-controls.mjs');s=p.read_text().replace(" if(rule.id==='wrap-prints'){", " if(rule.id.startsWith('design-')&&rule.id!=='design-services'){const sync=()=>{const b=box.querySelector('[data-rule-add]'),q=box.querySelector('[data-quote]');b.hidden=values.purchase===0;q.textContent=values.purchase===0?'Quote price':'Get exact quote';q.dataset.quote='Vehicle Wraps';};box.addEventListener('change',sync);sync();}\n if(rule.id==='wrap-prints'){");p.write_text(s)
for p in ['dist/server/service-pages.mjs','dist/client/services-ui.mjs']:
 s=Path(p).read_text().replace("||rule.id==='design-services';", "||rule.id==='design-services'||rule.id.startsWith('design-');");s=s.replace("getValues().design||rule.id==='design-services'", "getValues().design||getValues().adjust||rule.id==='design-services'").replace("values.design||rule.id==='design-services'", "values.design||values.adjust||rule.id==='design-services'");Path(p).write_text(s)
# Extra design previews remain outside the pricing form and support CMS edits.
p=Path('dist/client/satin/assets/satin.9464926f1bc9.js');s=p.read_text().replace('sec(`<div class="cfg"><div class="opts"><span class="eyebrow plain">Make it yours', 'sec(`<div class="grid g3 design-preview-gallery">${["van","pickup","box"].map(v=>`<article class="card">${vehicleSVG(v,{c:d.c,text:d.name.toUpperCase()})}<p>${v===\'box\'?\'Box truck\':v} · design illustration</p></article>`).join(\'\')}</div>`) + sec(`<div class="cfg"><div class="opts"><span class="eyebrow plain">Make it yours');p.write_text(s)
# Independent checkbox filters in a left sidebar.
p=Path('dist/client/batch-pages.mjs');s=p.read_text().replace(" if(path==='/website-design')", """ if(path==='/shop/vehicle-wrap-designs'){const filters=root.querySelector('[data-filters]'),grid=root.querySelector('[data-designs]');if(filters&&grid){const layout=document.createElement('div');layout.className='shop-filter-layout';grid.before(layout);const sidebar=document.createElement('aside');sidebar.className='shop-filter-list';const cards=[...grid.children],keys=[['style','Style'],['ind','Industry'],['col','Colour']];sidebar.innerHTML='<h3>Filter designs</h3>'+keys.map(([key,label])=>`<fieldset><legend>${label}</legend>${[...new Set(cards.map(c=>c.dataset[key]))].map(value=>`<label><input type="checkbox" data-filter-key="${key}" value="${esc(value)}">${esc(value)}</label>`).join('')}</fieldset>`).join('');layout.append(sidebar,grid);filters.remove();sidebar.onchange=()=>{let count=0;cards.forEach(c=>{c.hidden=!keys.every(([key])=>{const selected=[...sidebar.querySelectorAll(`[data-filter-key="${key}"]:checked`)].map(x=>x.value);return !selected.length||selected.includes(c.dataset[key]);});if(!c.hidden)count++;});root.querySelector('[data-count]').textContent=count;root.querySelector('[data-empty]').hidden=!!count;};}}
 if(path==='/website-design')""");p.write_text(s)
# Template request uses the real persisted quote flow.
p=Path('dist/client/studio/catalog.mjs');s=p.read_text();s=s.replace("actions.add?.({name:'Vehicle template request',lines:[s.year+' '+s.make+' '+s.model,s.trim,s.body,'Availability and price to be confirmed'],total:0})", "window.satinOpenQuote?.('Vehicle template request','Vehicle: '+s.year+' '+s.make+' '+s.model+';Trim: '+s.trim+';Body: '+s.body)")
p.write_text(s)
# Checkout keeps the existing header and actual menus.
shell=Path('dist/client/satin/index.html').read_text();header=shell[shell.index('<header'):shell.index('<main')]
p=Path('dist/client/checkout/index.html');s=p.read_text();a=s.index('<header');b=s.index('</header>',a)+len('</header>');s=s[:a]+header+'<div class="drawer" data-drawer></div>'+s[b:];s=s.replace('</head>','<link rel="stylesheet" href="/satin/assets/satin.9b1d91238d6b.css"><link rel="stylesheet" href="/batch.css"></head>');s=s.replace('Print checkout |','Checkout |').replace('PRINT ORDERS','YOUR ORDER').replace('Loading your print order','Loading your order');s=s.replace('<script type="module" src="/checkout/checkout.mjs">', '<script type="module" src="/checkout/navigation.mjs"></script><script type="module" src="/checkout/checkout.mjs">');p.write_text(s)
p=Path('dist/server/index.js');s=p.read_text().replace("if(/^\\/satin(?:\\/(fa|fr|es))?\\/checkout\\/?$/.test(url.pathname)) return env.ASSETS.fetch(new Request(new URL('/checkout/index.html',url),request));", "if(/^(?:\\/satin(?:\\/(fa|fr|es))?)?\\/checkout\\/?$/.test(url.pathname)){return renderNavigation(await env.ASSETS.fetch(new Request(new URL('/checkout/index.html',url),request)),request,env);}");p.write_text(s)
# Billing address can match shipping or be supplied separately.
p=Path('dist/client/checkout/checkout.mjs');s=p.read_text().replace('<div class="actions"><button type="submit" class="btn">Calculate delivery options', '<fieldset><legend>Billing address</legend><label><input type="checkbox" name="billingSame" checked> Same as shipping</label><div data-billing-fields hidden>${[\'name\',\'street1\',\'street2\',\'city\',\'state\',\'zip\'].map(k=>`<label class="field">${k}<input name="billing_${k}" maxlength="160" value="${esc(draft().billingAddress?.[k]||\'\')}"></label>`).join(\'\')}</div></fieldset><div class="actions"><button type="submit" class="btn">Calculate delivery options');s=s.replace("document.addEventListener('change',e=>{", "document.addEventListener('change',e=>{if(e.target.name==='billingSame'){document.querySelector('[data-billing-fields]').hidden=e.target.checked;document.querySelectorAll('[data-billing-fields] input').forEach(i=>i.required=!e.target.checked&&![\'billing_street2\'].includes(i.name));}");s=s.replace("await mutate('shipping',{address:a});", "const billing=a.billingSame==='on'?a:{...Object.fromEntries(['name','street1','street2','city','state','zip'].map(k=>[k,a['billing_'+k]])),email:a.email,country:'CA'};await mutate('shipping',{address:a,billingAddress:billing});");p.write_text(s)
p=Path('dist/server/checkout/routes.mjs');s=p.read_text().replace("draft.address.zip=draft.address.zip.toUpperCase();", "draft.address.zip=draft.address.zip.toUpperCase();const billing=v.billingAddress||a;if(!clean(billing.name)||!clean(billing.street1)||!clean(billing.city)||!/^\\w\\d\\w ?\\d\\w\\d$/i.test(billing.zip||''))throw Error('Complete your billing address.');draft.billingAddress=Object.fromEntries(['name','email','street1','street2','city','state','zip','country'].map(k=>[k,clean(billing[k],160)]));");p.write_text(s)
