from pathlib import Path
for p in ['dist/server/pricing-form.mjs','dist/client/pricing-form.mjs']:
 s=Path(p).read_text();s=s.replace("r.id==='window-graphics'||r.id==='wallpaper'", "r.id==='window-graphics'||r.id==='tint-commercial'||r.id==='wallpaper'")
 s=s.replace('>Add to quote cart</button>',">${wrap?'Get exact quote':'Add to cart'}</button>")
 s=s.replace('<button class="btn block" data-rule-add>', '<button class="btn block" data-rule-add ${wrap?\'hidden\':\'\'}>')
 s=s.replace('${wrap?\'Vehicle Wraps\':glass?\'Window Graphics\':\'Wallpaper\'}', '${wrap?\'Vehicle Wraps\':rule.id===\'tint-commercial\'?\'Window Tint\':glass?\'Window Graphics\':\'Wallpaper\'}')
 s=s.replace('f.key===\'quantity\'&&product?.quantity?.length','f.key===\'quantity\'&&!rule.path.includes(\'/large-format/\')&&product?.quantity?.length')
 s=s.replace('style="margin-top:16px">Add to cart</button>', 'style="margin-top:16px" ${rule.id.startsWith(\'ppf-\')||rule.id===\'tint-vehicle\'?\'hidden\':\'\'}>Add to cart</button><button class="btn ghost block" data-quote="${rule.id.startsWith(\'ppf-\')?\'Vehicle Wraps\':rule.id.startsWith(\'tint-\')?\'Window Tint\':rule.path.includes(\'/apparel\')?\'Apparel\':rule.path.includes(\'/print-shop\')?\'Print Shop\':\'Shop / General\'}">Get exact quote</button>')
 Path(p).write_text(s)
p='dist/client/studio/calculator.mjs';s=Path(p).read_text();s="import {mountBatchControls} from '/batch-controls.mjs';\n"+s
s=s.replace('artwork=null,upload=null,mode=', 'artwork=null,upload=null,uploads=[],mode=')
a=s.index("if(mode==='upload')$('[data-art-controls]').innerHTML=");b=s.index("if(mode==='designer')",a)
s=s[:a]+"if(mode==='upload'){const apparel=rule.id.startsWith('apparel-')||rule.id==='dtf-transfers',wall=rule.id==='wallpaper-custom';$('[data-art-controls]').innerHTML=`<input type=\"file\" data-art-upload multiple accept=\"${apparel?'image/png,image/svg+xml':wall?'image/png,image/jpeg,image/webp':'image/png,image/jpeg,image/webp,application/pdf,image/svg+xml'}\"><p class=\"small\">${apparel?'PNG or SVG':wall?'Image files only':'PNG, JPG, WebP, SVG or PDF'} · maximum 20 MB per file</p><div data-file-checks></div><label class=\"artwork-consent\"><input type=\"checkbox\" data-art-accept> I confirm my files and understand that print quality or artwork issues remain my responsibility. Production review may identify further issues.</label><p class=\"small\">Support: <a href=\"mailto:info@satingraphic.ca\">info@satingraphic.ca</a></p>`;}"+s[b:]
a=s.index("const f=e.target.files[0];if(!f)return;");b=s.index("};box.oninput",a)
s=s[:a]+"const files=[...e.target.files];if(!files.length)return;try{if(files.some(f=>f.size>20000000))throw Error('Each upload must be smaller than 20 MB.');$('[data-art-status]').textContent='Saving artwork…';await studioAPI('session',{});uploads=[];for(const f of files){const fd=new FormData();fd.set('file',f);fd.set('product',rule.id);const r=await fetch('/api/studio/upload',{method:'POST',body:fd}),v=await r.json();if(!r.ok)throw Error(v.error);uploads.push(v.file);}upload=uploads[0];$('[data-art-status]').textContent=uploads.map(f=>f.name).join(' · ');artwork=null;$('[data-art-preview]').innerHTML='';const cr=await fetch('/api/artwork/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ruleId:rule.id,values,fileIds:uploads.map(f=>f.id)})}),checks=await cr.json();$('[data-file-checks]').innerHTML=(checks.reports||[]).map(r=>`<details open><summary>${esc(r.name)} · ${esc(r.status)}</summary><p>${esc(r.message||'File structure and dimensions checked; confirm colour, resolution and fonts before production.')}</p>${(r.pages||[]).map(p=>p.checks.map(c=>`<p>${esc(c.name)}: ${esc(c.detail)}</p>`).join('')).join('')}</details>`).join('');}catch(err){$('[data-art-status]').textContent=err.message;}}"+s[b:]
s=s.replace("if(!quote)return;", "if(!quote)return;if(rule.id==='wrap-prints'&&values.kind===1&&values.height>48){$('[data-price-error]').textContent='Cut decals have a maximum height of 48 inches.';return;}if(upload&&!$('[data-art-accept]')?.checked){$('[data-price-error]').textContent='Confirm your artwork and responsibility for file issues before adding to cart.';return;}")
s=s.replace("artwork:artwork?{designId:artwork.id}:upload?{fileId:upload.id}:null,pricing:", "artworkAccepted:!!artwork||!!$('[data-art-accept]')?.checked||!configured?.artwork,artwork:artwork?{designId:artwork.id}:upload?{fileId:upload.id,fileIds:uploads.map(f=>f.id)}:null,pricing:")
s=s.replace("if(product?.group==='Offset print'){location.assign('/satin/checkout/');return;}","if(!rule.priceOnRequest){location.assign('/satin/checkout/');return;}")
s=s.replace("`inset(0 ${Math.round((1-coverage)*100)}% 0 0)`", "`inset(0 ${Math.round((1-(coverage===.45?.5:coverage===.7?.75:coverage))*100)}% 0 0)`")
s=s.replace('controls();summary();await recalc();', 'controls();mountBatchControls(box,rule,values,()=>{summary();recalc();});summary();await recalc();')
Path(p).write_text(s)
