from pathlib import Path
# Apparel sleeve designs are real saved surfaces, not just decorative tabs.
for p in ['dist/server/studio-model.mjs','dist/client/studio/model.mjs']:
 s=Path(p).read_text().replace('design.sides.length!==2','!(product?.group===\'Apparel\'?[2,4]:[2]).includes(design.sides.length)').replace('![1,2].includes(design.options.sideCount)',"!(product?.group==='Apparel'?[1,2,4]:[1,2]).includes(design.options.sideCount)")
 Path(p).write_text(s)
p=Path('dist/server/studio.mjs');s=p.read_text().replace("i<(design.options.sideCount===1?1:2)","i<design.options.sideCount").replace("(i===0?'front-outside':'back-inside')", "(['front-outside','back-inside','left-sleeve','right-sleeve'][i])");p.write_text(s)
p=Path('dist/client/studio/designer.mjs');s=p.read_text()
s=s.replace("sides:[{background:'#ffffff',layers:[]},{background:'#ffffff',layers:[]}]", "sides:Array.from({length:product.group==='Apparel'?4:2},()=>({background:'#ffffff',layers:[]}))")
s=s.replace('<h2>Add to your design</h2>', '<h2>Add to your design</h2><div data-text-controls class="studio-text-controls"><p>Select a text layer to edit its font and colour.</p></div>')
s=s.replace('PNG, JPG, WebP or PDF · maximum 20 MB','${product.group===\'Apparel\'?\'PNG or SVG\':\'PNG, JPG, WebP or PDF\'} · maximum 20 MB')
s=s.replace('accept="image/png,image/jpeg,image/webp,application/pdf"', 'accept="${product.group===\'Apparel\'?\'image/png,image/svg+xml\':\'image/png,image/jpeg,image/webp,application/pdf\'}"')
s=s.replace('<button class="studio-action" data-side="1">Back / inside</button>', '<button class="studio-action" data-side="1">Back / inside</button>${product.group===\'Apparel\'?\'<button class="studio-action" data-side="2">Left sleeve</button><button class="studio-action" data-side="3">Right sleeve</button>\':\'\'}')
s=s.replace("garmentSwatches(rule,d.values,'data-extra-field')+garmentSizes(rule,d.values,'data-extra-field')+", "(fromProduct?'':garmentSwatches(rule,d.values,'data-extra-field')+garmentSizes(rule,d.values,'data-extra-field'))+")
a=s.index('function syncApparelSides()');b=s.index('\nfunction renderStage',a)
s=s[:a]+"function syncApparelSides(){if(product.group!=='Apparel'||!rule)return;while(design.sides.length<4)design.sides.push({background:'#ffffff',layers:[]});design.options.sideCount=4;for(const b of host.querySelectorAll('[data-side]')){b.hidden=false;b.textContent=['Front','Back / inside','Left sleeve','Right sleeve'][+b.dataset.side];}}"+s[b:]
s=s.replace("stage.dataset.vehicle=product.id;", "stage.classList.toggle('garment-stage',product.group==='Apparel');stage.dataset.hat=product.garment?.group==='hats';if(product.group==='Apparel')stage.style.backgroundImage=`url('${garmentPhoto(product.id,design.options.values.colour||0,side===1?'back':'front')}')`;stage.dataset.vehicle=product.id;")
s=s.replace("svg.append(r);}$('[data-dimensions]')", "svg.append(r);const handle=document.createElementNS('http://www.w3.org/2000/svg','circle');handle.setAttribute('cx',(layer.x+layer.w)*W);handle.setAttribute('cy',(layer.y+layer.h)*H);handle.setAttribute('r',W/55);handle.setAttribute('fill','#df2865');handle.dataset.resize=layer.id;handle.style.cursor='nwse-resize';svg.append(handle);}$('[data-dimensions]')")
s=s.replace("fd.set('file',f);const r=await fetch('/api/studio/upload'", "fd.set('file',f);fd.set('product',product.id);const r=await fetch('/api/studio/upload'")
s=s.replace("if(!l){$('[data-properties]').innerHTML=", "if(!l){if($('[data-text-controls]'))$('[data-text-controls]').innerHTML='<p>Select a text layer to edit its font and colour.</p>';$('[data-properties]').innerHTML=")
# Mirror text editing into Add to your design; existing delegated input handler updates the real layer.
s=s.replace("function renderProperties(){const l=currentLayer();", "function renderProperties(){const l=currentLayer();if(l&&$('[data-text-controls]'))$('[data-text-controls]').innerHTML=l.type==='text'?`<label>Text<textarea data-property=\"text\" rows=\"2\">${esc(l.text)}</textarea></label><label>Font<select data-property=\"font\">${FONTS.map(f=>`<option ${f===l.font?'selected':''}>${f}</option>`).join('')}</select></label><label>Text colour<input type=\"color\" data-property=\"color\" value=\"${l.color}\"></label><label>Font size<input type=\"number\" data-property=\"fontSize\" min=\"4\" max=\"500\" value=\"${l.fontSize}\"></label>`:'<p>Select a text layer to edit its font and colour.</p>';")
s=s.replace("const group=e.target.closest('[data-layer]');if(!group)", "const resize=e.target.closest('[data-resize]'),group=e.target.closest('[data-layer]');if(resize)selected=resize.dataset.resize;if(!group&&!resize)").replace('selected=group.dataset.layer;', 'if(group)selected=group.dataset.layer;')
s=s.replace("drag={id:selected,x:e.clientX,y:e.clientY,ox:l.x,oy:l.y,w:r.width,h:r.height};", "drag={id:selected,resize:!!resize,x:e.clientX,y:e.clientY,ox:l.x,oy:l.y,ow:l.w,oh:l.h,w:r.width,h:r.height};")
s=s.replace("l.x=Math.max(-1,Math.min(2,drag.ox+(e.clientX-drag.x)/drag.w));l.y=Math.max(-1,Math.min(2,drag.oy+(e.clientY-drag.y)/drag.h));", "if(drag.resize){l.w=Math.max(.01,Math.min(4,drag.ow+(e.clientX-drag.x)/drag.w));l.h=Math.max(.01,Math.min(4,drag.oh+(e.clientY-drag.y)/drag.h));}else{l.x=Math.max(-1,Math.min(2,drag.ox+(e.clientX-drag.x)/drag.w));l.y=Math.max(-1,Math.min(2,drag.oy+(e.clientY-drag.y)/drag.h));}")
# Artwork is composited into fabric lighting, with an illustrative stitched surface for embroidery.
s=s.replace("ctx.drawImage(art,x,y,aw,ah);return", "ctx.save();ctx.globalCompositeOperation='multiply';ctx.drawImage(art,x,y,aw,ah);ctx.restore();const method=p.options.find(o=>o.key==='method')?.options.find(o=>o.value===model.options.values.method)?.label||'';if(/embroidery/i.test(method)){const thread=document.createElement('canvas');thread.width=art.width;thread.height=art.height;const tc=thread.getContext('2d');tc.drawImage(art,0,0);tc.globalCompositeOperation='source-atop';for(let y=0;y<art.height;y+=4){tc.strokeStyle=y%8?'#ffffff55':'#00000035';tc.lineWidth=1.4;tc.beginPath();tc.moveTo(0,y);tc.lineTo(art.width,y+art.width*.08);tc.stroke();}ctx.drawImage(thread,x,y,aw,ah);}if(model.sides.length===4){for(const i of [2,3])if(model.sides[i].layers.length){const svg=svgArtwork(model,i,embedded,fonts,false),blob=new Blob([svg],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);try{const sleeve=await loadImage(url);ctx.save();ctx.globalCompositeOperation='multiply';const sw=w*.12;ctx.drawImage(sleeve,i===2?600-w*.32:600+w*.2,600-h*.23,sw,sw*sleeve.height/sleeve.width);ctx.restore();}finally{URL.revokeObjectURL(url);}}}return")
p.write_text(s)
