from pathlib import Path
import shutil
for name in ['satin-shirt','window-vinyl','vehicle-wrap-tools','wall-room']:
 shutil.copy('../generated-assets/'+name+'.png','dist/client/satin/img/'+name+'.png')
shutil.copy('dist/server/transparent-images.mjs','dist/client/transparent-images.mjs')
# One navigation model serves desktop, mobile and the menu editor, with a one-time default migration.
for p in ['dist/server/site-navigation.mjs','dist/client/site-navigation.mjs']:
 s=Path(p).read_text().replace('<summary>${esc(m.label)}</summary>','<summary class="${m.key===\'wraps\'?\'wraps-nav\':\'\'}">${esc(m.label)}</summary>')
 s+='\nexport function migrateNavigation(items){const rows=structuredClone(items);for(const m of rows){if(m.key===\'apparel\')for(const g of m.groups||[]){g.links=g.links.filter(l=>l.label!==\'DTF print\');for(const l of g.links)if(l.label===\'DTF transfer\')l.href=\'/satin/shop/dtf-transfers\';}if(m.key===\'print\'){const g=m.groups.find(g=>g.label===\'Large Format\');if(g&&!g.links.some(l=>l.href.includes(\'poly-bag\')))g.links.push({label:\'Poly Bag Lawn Sign\',href:\'/satin/print-shop/large-format/poly-bag-lawn-sign\',active:true});}if(m.key===\'shop\'){const g=m.groups.find(g=>g.label===\'Services\');if(g)for(const [label,href] of [[\'Social Media\',\'/satin/social-media-services\'],[\'Videography\',\'/satin/videography\']])if(!g.links.some(l=>l.href===href))g.links.push({label,href,active:true});}}if(!rows.some(m=>m.key===\'login\'))rows.push({key:\'login\',label:\'Log in\',href:\'/satin/login\',active:true,groups:[]});return rows;}\nDEFAULT_NAVIGATION.splice(0,DEFAULT_NAVIGATION.length,...migrateNavigation(DEFAULT_NAVIGATION));\n'
 Path(p).write_text(s)
p='dist/server/navigation.mjs';s=Path(p).read_text().replace('DEFAULT_NAVIGATION,menuHTML','DEFAULT_NAVIGATION,menuHTML,migrateNavigation');s=s.replace('return row?JSON.parse(row.value):{items:DEFAULT_NAVIGATION,revision:0};','if(!row)return {items:DEFAULT_NAVIGATION,revision:0,batchVersion:1};const value=JSON.parse(row.value);return value.batchVersion?value:{...value,items:migrateNavigation(value.items),batchVersion:1};');s=s.replace('const value={items:v.items,revision:prior.revision+1}', 'const value={items:v.items,revision:prior.revision+1,batchVersion:1}');# prior CAS must compare original serialized value, migration changes shape
s=s.replace("JSON.stringify(prior)).run()", "(await env.DB.prepare('SELECT value FROM site_settings WHERE key = ?').bind('navigation').first())?.value||JSON.stringify(prior)).run()")
Path(p).write_text(s)
# Promo slides use a simple owner-editable list in Service settings.
p='dist/server/service-defaults.mjs';s=Path(p).read_text().replace('export const SETTINGS={','export const SETTINGS={\n promotions:[{title:"Your next project starts here.",text:"Vehicle wraps, print and custom apparel from one team.",button:"Get exact quote",link:"/satin/contact",image:"/satin/img/job-greenlife-van.jpg",active:true}],');Path(p).write_text(s)
p='dist/server/services.mjs';s=Path(p).read_text();s=s.replace("const old=await serviceSettings", "if('promotions' in v){if(!Array.isArray(v.promotions)||v.promotions.length>12||v.promotions.some(p=>!str(p.title,160)||!safeURL(p.image)||!/^\\/satin(?:\\/|$)/.test(p.link)))throw Error('Check promotion title, image and button link');}\nconst old=await serviceSettings");s=s.replace("for(const k of ['bookingDays'", "if('promotions' in v)out.promotions=v.promotions.map(p=>({title:str(p.title,160),text:str(p.text,600),button:str(p.button,80),link:p.link,image:p.image,active:p.active!==false}));\nfor(const k of ['bookingDays'");Path(p).write_text(s)
p='dist/client/admin/services.mjs';s=Path(p).read_text().replace('<h2>Appointment times · Toronto</h2>', '<h2>Home promotion slider</h2><p>Edit title, text, button, link and image for every slide. Each line below is one slide; drag the slide rows to reorder them.</p><div data-promotions></div><button type="button" data-promo-add>Add promotion</button><h2>Appointment times · Toronto</h2>');s=s.replace("root.onchange=async e=>", "const promos=structuredClone(s.promotions||[]);const promoArea=root.querySelector('[data-promotions]');let dragged=-1;const paintPromos=()=>{promoArea.innerHTML=promos.map((p,i)=>`<fieldset draggable=\"true\" data-promo=\"${i}\"><legend>Slide ${i+1}</legend>${['title','text','button','link','image'].map(k=>`<label>${k}<input data-promo-key=\"${k}\" value=\"${esc(p[k])}\"></label>`).join('')}<label><input type=\"checkbox\" data-promo-key=\"active\" ${p.active!==false?'checked':''}>Active</label><label>Upload image<input type=\"file\" data-promo-image accept=\"image/png,image/jpeg,image/webp\"></label><button type=\"button\" data-promo-remove>Remove slide</button></fieldset>`).join('');};paintPromos();promoArea.oninput=e=>{const row=e.target.closest('[data-promo]'),key=e.target.dataset.promoKey;if(row&&key)promos[+row.dataset.promo][key]=key==='active'?e.target.checked:e.target.value;};promoArea.onclick=e=>{const row=e.target.closest('[data-promo]');if(row&&e.target.hasAttribute('data-promo-remove')){promos.splice(+row.dataset.promo,1);paintPromos();}};promoArea.ondragstart=e=>{dragged=+e.target.closest('[data-promo]').dataset.promo;};promoArea.ondragover=e=>e.preventDefault();promoArea.ondrop=e=>{e.preventDefault();const row=e.target.closest('[data-promo]');if(row&&dragged>=0){const [p]=promos.splice(dragged,1);promos.splice(+row.dataset.promo,0,p);paintPromos();}};root.querySelector('[data-promo-add]').onclick=()=>{promos.push({title:'New promotion',text:'',button:'Learn more',link:'/satin/contact',image:'/satin/img/window-vinyl.png',active:true});paintPromos();};\nroot.onchange=async e=>")
s=s.replace("const k=e.target.dataset.banner", "if(e.target.hasAttribute('data-promo-image')){try{const i=+e.target.closest('[data-promo]').dataset.promo;promos[i].image=await upload(e.target.files[0]);paintPromos();}catch(err){message(err.message,true);}return;}const k=e.target.dataset.banner")
s=s.replace('const fd=new FormData(e.target),v={...s};','const fd=new FormData(e.target),v={...s,promotions:promos};');Path(p).write_text(s)
# Fix missing transparent image import, direct category links, coherent finishes.
for p in ['dist/server/service-pages.mjs','dist/client/services-ui.mjs']:
 s=Path(p).read_text().replace('const transparentImages=[];', "import {transparentImages} from './transparent-images.mjs';")
 s=s.replace("'hats-caps':'hats'", "'hats-caps':'hats','hats':'hats','sweatshirts':'sweatshirts','polos':'polos','totes':'totes','long-sleeves':'long-sleeves'")
 s=s.replace("data-initial-category=\"${initial}\"", "data-initial-category=\"${initial}\" data-initial-group=\"${['men','women','youth','hats','totes'].includes(path.split('/')[2])?path.split('/')[2]:'all'}\"")
 s=s.replace("let group='all';", "let group=apparel.dataset.initialGroup||'all';")
 s=s.replace("['graphite','#555960'],['red','#b51629']", "['graphite','#555960'],['red','#b51629'],['pink','#e88ba8']")
 s=s.replace('${c[0].toUpperCase()+c.slice(1)}', "${c==='graphite'?'Dark grey':c[0].toUpperCase()+c.slice(1)}")
 s=s.replace('<p>Matte and Satin add 10% to the wrap price. Optional design services add $250 afterward.</p>','')
 s=s.replace("im.src='/satin/img/tesla-'+colour+'-'+finish+'.png';", "im.src='/satin/img/tesla-'+(colour==='pink'?'red':colour)+'-'+finish+'.png';im.style.filter=colour==='pink'?'hue-rotate(330deg) saturate(.65) brightness(1.25)':'';")
 s=s.replace("if(path==='/window-graphics'){root.querySelectorAll('.art')", "if(path==='/window-graphics'){for(const h of root.querySelectorAll('h2,h3'))if(h.textContent.trim()==='Measure the glass')h.closest('section')?.remove();root.querySelectorAll('.art')")
 # New product route is a normal CMS/catalog page.
 s=s.replace("if(path.startsWith('/apparel'))", "if(['/print-shop/large-format/poly-bag-lawn-sign','/shop/dtf-transfers'].includes(path)){const p=records.find(p=>p.path==='/satin'+path);return {title:p?.name||'Custom print',html:section(`<span class=\"eyebrow\">Custom print</span><h1 class=\"d1\">${esc(p?.name||'Custom print')}</h1><p class=\"lede\">${esc(p?.description||'Choose your size and quantity, then upload artwork or request design services.')}</p><div class=\"cfg\"></div>`)};}\nif(path.startsWith('/apparel'))")
 Path(p).write_text(s)
p='dist/server/index.js';s=Path(p).read_text().replace("if(customPath.startsWith('/apparel')", "if(['/print-shop/large-format/poly-bag-lawn-sign','/shop/dtf-transfers'].includes(customPath)||customPath.startsWith('/apparel')");Path(p).write_text(s)
p='dist/client/satin/assets/satin.9464926f1bc9.js';s=Path(p).read_text().replace("i<3?' active'", "i<2?' active'").replace('${i>=3}', '${i>=2}').replace("${i>=3?'tabindex", "${i>=2?'tabindex").replace('const active=[0,1,2]','const active=[0,1]').replace('(current+3)%order.length','(current+2)%order.length');Path(p).write_text(s)
